name: Release

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install
      - uses: nrwl/nx-set-shas@v4

      - name: Install global dependencies
        run: pnpm install --global nx

      - name: Nx affected build and test
        run: |
          nx affected -t build

      - name: Release and eventually publish
        run: nx release publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

